# Generated by Django 2.2.5 on 2020-01-29 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_verification', models.CharField(max_length=20)),
                ('form', models.FileField(upload_to='')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='')),
                ('aadhar_no', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('process_complete', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of', models.CharField(max_length=20)),
                ('type_of', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=4)),
                ('expiry', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FIRDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_victim', models.CharField(max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=16, null=True)),
                ('description_of_incidence', models.TextField(blank=True, null=True)),
                ('location_of_crime', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime_of_crime', models.DateTimeField(blank=True, null=True)),
                ('witness_name', models.CharField(blank=True, max_length=100, null=True)),
                ('witness_aadhar', models.CharField(blank=True, max_length=100, null=True)),
                ('identified_accused', models.TextField(blank=True, null=True)),
                ('type_of_crime', models.CharField(max_length=50)),
                ('datetime_of_FIR', models.DateTimeField(auto_now=True)),
                ('passed_to_CCTNS', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('sign', models.FileField(blank=True, null=True, upload_to='')),
                ('police_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PoliceStationDetail')),
            ],
        ),
    ]
