# Generated by Django 2.2.5 on 2020-01-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cybercrime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybercrime',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='passed_to_CC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firdetail',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
